move to gae app

diff --git a/docs/bower_components/app-layout/.travis.yml b/docs/bower_components/app-layout/.travis.yml
--- a/docs/bower_components/app-layout/.travis.yml
+++ b/docs/bower_components/app-layout/.travis.yml
@@ -1,8 +1,9 @@
 language: node_js
 sudo: required
 dist: trusty
-node_js: '6'
+node_js: stable
 addons:
+  sauce_connect: true
   firefox: latest
   apt:
     sources:
@@ -10,11 +11,20 @@ addons:
     packages:
       - google-chrome-stable
 before_script:
-  - npm install -g bower polylint web-component-tester
-  - bower install
+  - npm install -g polymer-cli
+  - polymer install --variants
+  - >-
+    npm run update-types && git diff --exit-code || (echo -e
+    '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
+    update-types".' && false)
+  - >-
+    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
+    Typings are stale. Please run "npm run format".' && false)
 script:
-  - xvfb-run wct
-  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s ''default''; fi'
+  - xvfb-run polymer test
+  - >-
+    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
+    fi
 env:
   global:
     - secure: >-
